# Generated by Django 4.0.1 on 2022-01-19 18:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_first_name_alter_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
