# Generated by Django 4.0.1 on 2022-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.JSONField(default={'lat': 0.0, 'lon': 0.0}),
            preserve_default=False,
        ),
    ]
