# Generated by Django 4.0.1 on 2022-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
