# Generated by Django 4.0.1 on 2022-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
