# Generated by Django 4.0.1 on 2022-01-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_location_client_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
